language: groovy
jdk:
  - oraclejdk8

install:
  - ./gradlew --version

script:
#  - "./gradlew check --info --stacktrace --continue"
  - git --version
  - echo "Do compilcated build logic"

  - git config --global user.email "4financebot@gmail.com"
  - git config --global user.name "4Finance Bot"
  - git config --global push.default simple
  - git remote set-url origin "https://${GH_TOKEN}@github.com/4finance/releasing-sandbox.git"
  - ./gradlew release

env:
  global:
    - TERM=dumb
    - secure: S39OzAmB8eajw0LNlVaDnB1xxlwcDZNrlbsA3CTYAPCkB/mJVCwyGcQsqYsrtWBh/7HpbjyLA/FE9G5n1Xa/vOUxRoN/OZJLVUOGNnHuJgLyVoO8mFk2gSc1cdzTjscRRKB2uRLB9tggWfOwlRXttRsSUfDRB/fDOm3uumgA2EU=
