before_install:
- git --version
- "echo $GRADLE_OPTS"
- "export GRADLE_OPTS='-Dorg.gradle.daemon=true'"
- "echo $TRAVIS_JDK_VERSION"
- "env"

install:
- ./gradlew assemble

script:
- set -e
- ./gradlew check --info --stacktrace --continue
- source build/release/gradle/setGitVariables.sh
- ./gradlew release -Prelease.disableRemoteCheck -Prelease.localOnly --info --stacktrace
- ./gradlew finalizeRelease publishUploadedArtifacts -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_API_KEY} --info --stacktrace
- if [ $DO_ACCEPTANCE_TESTS == true ]; then ./gradle/runBootMicroserviceAcceptanceTests.sh; fi

language: groovy

matrix:
  include:
    # Release not skipped only in Java 7 build
    - jdk: oraclejdk7
      env: SKIP_RELEASE=false
    # Build on Java 8 with acceptance tests in micro
    - jdk: oraclejdk8
      env: DO_ACCEPTANCE_TESTS=true

env:
  global:
  - TERM=dumb
  - SKIP_RELEASE=true
  - secure: JRfoEx1ZzMAo0+QW8tZz0i7aH5HkpIeyFDModEgk1XqCT6YnjEl0Q45GdkM97RfBtQbfcVImKJpYDX+9EEjEEN1lgS4VOMc/ZjDQ2LUvJGDUYNK+Umc4Lkg4FSfLIMqB4rNwW8fg9n7tqjewMalIEAVKsVeDmYmcyJzv7hlIJR8=
  - secure: XhmAkMz9LdKiRNnUozxDjWTfr4/qyUP1YKiCXoYbkFd+lU/GddEQQCc6r9HyM0J2HLNuiSEoxJ6DUWHZoYd1b2MWsfibHB9TnPgMdjqScPPTnFg1OiIETze7mP168TTMZ9dfSk2iDwqmnjsZ/O9YBd8Aff+GpLiIczqgkveyzio=
  - secure: OjjfTYJcsNAJ2HjJIkvPlWKm4dF+5RW4bbpjIXFRBDFZO+U4AOdov64BqEnHRgdJW5oGn+2mKpkAU6wu7x76UXQUeuMFlqGoCdxAJdynNrTdPOiQ+cXINngCvdGO0pM6F24K6NpS6jWJiXpu6tIQZz1A+qCEKuls8ujby89pV/c=
