language: groovy
jdk:
  - oraclejdk8

install:
  - ./gradlew --version

script:
#  - "./gradlew check --info --stacktrace --continue"
  - git --version
  - echo "Do compilcated build logic"

  - git config user.email "4financebot@gmail.com"
  - git config user.name "4Finance Bot"
  - git config push.default simple
  - git remote set-url origin "https://${GH_TOKEN}@github.com/4finance/releasing-sandbox.git"
  - ./gradlew release -Prelease.disableRemoteCheck -Prelease.localOnly --info --stacktrace
#Manual push to workaround: https://github.com/allegro/axion-release-plugin/issues/32
  - git push origin HEAD:${TRAVIS_BRANCH}
  - git push origin --tags


env:
  global:
    - TERM=dumb
    - secure: S39OzAmB8eajw0LNlVaDnB1xxlwcDZNrlbsA3CTYAPCkB/mJVCwyGcQsqYsrtWBh/7HpbjyLA/FE9G5n1Xa/vOUxRoN/OZJLVUOGNnHuJgLyVoO8mFk2gSc1cdzTjscRRKB2uRLB9tggWfOwlRXttRsSUfDRB/fDOm3uumgA2EU=
